const ACTION_LABELS: Record<string, string> = {
  LOGIN_SUCCESS: 'Login realizado',
  LOGIN_FAILED: 'Falha no login',
  LOGOUT: 'Logout realizado',
  USER_CREATED: 'Usuário criado',
  USER_UPDATED: 'Usuário atualizado',
  USER_DELETED: 'Usuário desativado',
  USER_RESTORED: 'Usuário restaurado',
  USER_SELF_UPDATED: 'Perfil atualizado',
  USER_PASSWORD_CHANGED: 'Senha alterada',
  EVENT_CREATED: 'Evento criado',
  EVENT_UPDATED: 'Evento atualizado',
  EVENT_DELETED: 'Evento excluído',
  EVENT_STATUS_CHANGED: 'Status do evento alterado',
  EVENT_TIEBREAKER_UPDATED: 'Desempate atualizado',
  EVENT_TIEBREAKER_REMOVED: 'Desempate removido',
  EVENT_CERTIFICATE_TEXT_UPDATED: 'Texto do certificado atualizado',
  CATEGORY_CREATED: 'Categoria criada',
  CATEGORY_UPDATED: 'Categoria atualizada',
  CATEGORY_DELETED: 'Categoria excluída',
  CATEGORIES_REORDERED: 'Categorias reordenadas',
  JUDGE_ADDED: 'Jurado adicionado',
  JUDGE_UPDATED: 'Jurado atualizado',
  JUDGE_REMOVED: 'Jurado removido',
  JUDGE_MATRIX_UPDATED: 'Matriz de jurados atualizada',
  PARTICIPANT_CREATED: 'Participante criado',
  PARTICIPANT_UPDATED: 'Participante atualizado',
  PARTICIPANT_DELETED: 'Participante excluído',
  PARTICIPANTS_REORDERED: 'Participantes reordenados',
  PARTICIPANT_PHOTO_UPLOADED: 'Foto do participante enviada',
  PARTICIPANT_PHOTO_REMOVED: 'Foto do participante removida',
  PARTICIPANT_MARKED_ABSENT: 'Participante marcado como ausente',
  PARTICIPANT_UNMARKED_ABSENT: 'Ausência removida do participante',
  PARTICIPANT_ACTIVATED: 'Participante ativado',
  SCORING_STARTED: 'Scoring iniciado',
  SCORES_REGISTERED: 'Notas registradas',
  JUDGE_CONFIRMED_SCORES: 'Jurado confirmou notas',
  JUDGE_REVISED_SCORES: 'Jurado revisou notas',
  JUDGE_FINALIZED_SCORES: 'Jurado finalizou notas',
  PARTICIPANT_FINISHED: 'Participante finalizado',
  REPORT_GENERATION_QUEUED: 'Relatório enfileirado',
  REPORT_GENERATION_COMPLETED: 'Relatório gerado',
  REPORT_GENERATION_FAILED: 'Falha na geração do relatório',
  REPORT_DOWNLOADED: 'Relatório baixado',
  CERTIFICATE_TEXT_UPDATED: 'Texto do certificado atualizado',
  CERTIFICATE_BACKGROUND_UPLOADED: 'Background do certificado enviado',
  CERTIFICATE_BACKGROUND_REMOVED: 'Background do certificado removido',
  CERTIFICATE_SIGNATURE_ADDED: 'Assinatura adicionada',
  CERTIFICATE_SIGNATURE_REMOVED: 'Assinatura removida',
  CERTIFICATE_BATCH_QUEUED: 'Geração de certificados enfileirada',
  CERTIFICATE_BATCH_COMPLETED: 'Certificados gerados',
  CERTIFICATE_BATCH_FAILED: 'Falha na geração de certificados',
  CERTIFICATE_BATCH_DOWNLOADED: 'Certificados baixados',
}

export function getActionLabel(action: string): string {
  return ACTION_LABELS[action] ?? action
}
